# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 1
set_param synth.incrementalSynthesisCache C:/Users/linsixing/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-8220-393A/incrSyn
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/linsixing/Documents/Vivado/RISCV-CPU/RISCV-CPU.cache/wt [current_project]
set_property parent.project_path C:/Users/linsixing/Documents/Vivado/RISCV-CPU/RISCV-CPU.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/linsixing/Documents/Vivado/RISCV-CPU/RISCV-CPU.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files x:/coe/riscv-studentnosorting.coe
read_verilog -library xil_defaultlib {
  C:/Users/linsixing/Documents/Vivado/RISCV-CPU/RISCV-CPU.srcs/sources_1/imports/CLK_DIV.v
  C:/Users/linsixing/Documents/Vivado/RISCV-CPU/RISCV-CPU.srcs/sources_1/imports/defines.v
  C:/Users/linsixing/Documents/Vivado/RISCV-CPU/RISCV-CPU.srcs/sources_1/imports/MIO_BUS.v
  C:/Users/linsixing/Documents/Vivado/RISCV-CPU/RISCV-CPU.srcs/sources_1/imports/MULTI_CH32.v
  C:/Users/linsixing/Documents/Vivado/RISCV-CPU/RISCV-CPU.srcs/sources_1/imports/SEG7x16.v
  C:/Users/linsixing/Documents/Vivado/RISCV-CPU/RISCV-CPU.srcs/sources_1/imports/alu.v
  C:/Users/linsixing/Documents/Vivado/RISCV-CPU/RISCV-CPU.srcs/sources_1/imports/control.v
  C:/Users/linsixing/Documents/Vivado/RISCV-CPU/RISCV-CPU.srcs/sources_1/imports/cpu.v
  C:/Users/linsixing/Documents/Vivado/RISCV-CPU/RISCV-CPU.srcs/sources_1/imports/forwarding.v
  C:/Users/linsixing/Documents/Vivado/RISCV-CPU/RISCV-CPU.srcs/sources_1/imports/hazard_detection.v
  C:/Users/linsixing/Documents/Vivado/RISCV-CPU/RISCV-CPU.srcs/sources_1/imports/imm.v
  C:/Users/linsixing/Documents/Vivado/RISCV-CPU/RISCV-CPU.srcs/sources_1/imports/memory.v
  C:/Users/linsixing/Documents/Vivado/RISCV-CPU/RISCV-CPU.srcs/sources_1/imports/mux.v
  C:/Users/linsixing/Documents/Vivado/RISCV-CPU/RISCV-CPU.srcs/sources_1/imports/pc.v
  C:/Users/linsixing/Documents/Vivado/RISCV-CPU/RISCV-CPU.srcs/sources_1/imports/pipeline_reg.v
  C:/Users/linsixing/Documents/Vivado/RISCV-CPU/RISCV-CPU.srcs/sources_1/imports/regfile.v
  C:/Users/linsixing/Documents/Vivado/RISCV-CPU/RISCV-CPU.srcs/sources_1/imports/fpga_top.v
}
read_ip -quiet C:/Users/linsixing/Documents/Vivado/RISCV-CPU/RISCV-CPU.srcs/sources_1/ip/imem/imem.xci
set_property used_in_implementation false [get_files -all c:/Users/linsixing/Documents/Vivado/RISCV-CPU/RISCV-CPU.srcs/sources_1/ip/imem/imem_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/linsixing/Documents/Vivado/RISCV-CPU/RISCV-CPU.srcs/constrs_1/imports/constraints/Nexys4DDR_CPU.xdc
set_property used_in_implementation false [get_files C:/Users/linsixing/Documents/Vivado/RISCV-CPU/RISCV-CPU.srcs/constrs_1/imports/constraints/Nexys4DDR_CPU.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top IP2SOC_Top -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef IP2SOC_Top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file IP2SOC_Top_utilization_synth.rpt -pb IP2SOC_Top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
